# Generated by Django 5.0.2 on 2024-06-08 22:26

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_actor_birthday_alter_analysis_result_and_more'),
        ('news', '0014_alter_new_publicationdate'),
        ('users', '0006_alter_strike_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(1888, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 6, 9))]),
        ),
        migrations.AlterField(
            model_name='strike',
            name='expiration_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1888, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 6, 9))]),
        ),
        migrations.AlterField(
            model_name='strike',
            name='new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strike', to='news.new'),
        ),
        migrations.AlterField(
            model_name='strike',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strike', to='movies.review'),
        ),
    ]
