# Generated by Django 5.0.2 on 2024-04-26 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique_for_date='publicationDate')),
                ('photo', models.ImageField(upload_to='images/')),
                ('publicationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('PUBLISHED', 'Published'), ('IN_DRAFT', 'In Draft'), ('IN_REVIEW', 'In Review'), ('FORBIDDEN', 'Forbidden'), ('DELETED', 'Deleted')], default='IN_REVIEW', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='news.category')),
            ],
        ),
    ]
