# Generated by Django 5.0.2 on 2024-04-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
    ]
