# Generated by Django 5.0.2 on 2024-04-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_categories_remove_new_slug_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='hateScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
