# Generated by Django 5.0.2 on 2024-06-01 10:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_publicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publicationDate',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(1888, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 6, 1, 12, 23, 30, 344257))]),
        ),
    ]
