# Generated by Django 5.0.2 on 2024-06-15 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_new_publicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='hateScore',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
