# Generated by Django 5.0.2 on 2024-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('MAN', 'Hombre'), ('WOMAN', 'Mujer'), ('OTHER', 'Otro')], default='MAN', max_length=50)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('principalImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
