# Generated by Django 5.0.2 on 2024-05-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='genre',
            new_name='gender',
        ),
    ]
