# Generated by Django 5.0.2 on 2024-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_image_alter_movie_image_actor_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='movies.Performance', to='movies.actor'),
        ),
    ]
