# Generated by Django 5.0.2 on 2024-03-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='principalImage',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='images',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.image'),
        ),
    ]
