# Generated by Django 5.0.2 on 2024-03-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_principalimage_alter_actor_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='images',
        ),
    ]
