# Generated by Django 5.0.2 on 2024-05-29 17:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_eye_color_actor_hair_color_actor_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1888, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 5, 29))]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actor',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1888, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 5, 29))]),
        ),
    ]
