# Generated by Django 5.0.2 on 2024-03-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='isPublicated',
        ),
        migrations.AddField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('IN_REVIEW', 'In Review'), ('DELETED', 'Deleted')], default='IN_REVIEW', max_length=50),
        ),
    ]
