# Generated by Django 5.0.2 on 2024-06-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_url_image_urls_image_is_visible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='urls',
            new_name='url',
        ),
    ]
