# Generated by Django 5.0.2 on 2024-06-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_rename_urls_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='HomeImage',
        ),
    ]
