# Generated by Django 5.0.2 on 2024-06-08 08:39

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_image_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
