# Generated by Django 5.0.2 on 2024-04-19 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_strike_expiration_date_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('IN_DRAFT', 'In Draft'), ('IN_REVIEW', 'In Review'), ('DELETED', 'Deleted')], default='IN_REVIEW', max_length=50),
        ),
    ]
