# Generated by Django 5.0.2 on 2024-06-08 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_budget_alter_movie_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='homeimage',
            old_name='is_visible',
            new_name='isVisible',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzes', to='movies.performance')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzes', to='movies.emotion')),
            ],
        ),
    ]
