# Generated by Django 5.0.2 on 2024-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_review_publicationdate_alter_review_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('IN_DRAFT', 'In Draft'), ('IN_REVIEW', 'In Review'), ('FORBIDDEN', 'Forbidden'), ('DELETED', 'Deleted')], default='IN_REVIEW', max_length=50),
        ),
    ]
