# Generated by Django 5.0.2 on 2024-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_review_publicationdate_alter_review_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(blank=True),
        ),
    ]
