# Generated by Django 5.0.2 on 2024-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_review_publicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
