# Generated by Django 5.0.2 on 2024-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_strike_new_alter_strike_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Strike',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
