# Generated by Django 5.0.2 on 2024-05-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('movies', '0017_remove_userprofile_user_delete_strike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='movies.Performance', to='analysis.actor'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
