# Generated by Django 5.0.2 on 2024-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='screenTime',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
