# Generated by Django 5.0.2 on 2024-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_performance_screentime_delete_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='screenTime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
