# Generated by Django 5.0.2 on 2024-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_performance_screentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='screenTime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
