name: Codacy Analysis

on:
  push:
    branches:
      - main
      - develop

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install Codacy Analysis CLI
        run: |
          python -m pip install --upgrade pip
          pip install codacy-coverage

      - name: Run Codacy analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          python-codacy-coverage -r .
